### ISSUE TITLE
Reduce the config logs to write only to the log if config is changed.

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#115]
In #102 introduced feature is nice, but now, a lot of Info level logs are created during each run. What is not ideal.

There should be a solution, to write out the config log only, in case something has been changed, so, there is a need to "reload" everything...there is a need for a log.

So, log the config if:
- First time the app is started (Init)
- Any time, one of the config value, defined in SB has been changed by the user

**Comment by Th0rstenf** [comment]
As the logs make my style of debugging hell, I'll take care of it on the current branch
