### ISSUE TITLE
Add a guessing game

### ISSUE THREAD

**Issue by Th0rstenf** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#121]
### Discussed in https://github.com/Th0rstenf/Rocksniffer-to-Streamer.bot-extension/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **Th0rstenf** January 17, 2024</sup>
As all data is already available, it should  be possible to integrate a guessing game where users can enter their prediction as soon a song has started e.g.
!guess 87.3
If the user guesses 87.3% accuracy
After a  configurable amount of time no further guesses are accepted.

After a song has ended, an action should be triggered and the winner should be saved in a variable.

</div>

**Comment by BoomSoMuch** [comment]
I have bits of code from other programmers who started similar projects. I can't even read them but I'm happy to share them. I'm guessing it might make more sense for you to start from scratch and do this all with your own code. But if there is any way I can help please let me know!

**Comment by Th0rstenf** [comment]
added with 0.3.0
