### ISSUE TITLE
highestHitStreak variable not populating

### ISSUE THREAD

**Issue by BoomSoMuch** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#122]
It's very likely that I am doing something wrong here. I can get the currentHitStreak variable to populate, but not the highestHitStreak.

**Comment by Th0rstenf** [comment]
I'm not entirely sure there is much that can be done wrong here. I assume you are using the latest release?

Unfortunately I won't have time to look into it soon, but maybe we can schedule a call at some point?

**Comment by Th0rstenf** [comment]
@BoomSoMuch When testing with the current guessing game branch, all of those variables seem to work as intended. Can you please double check if the problem still persists for you?

**Comment by BoomSoMuch** [comment]
@Th0rstenf I'm closing this issue as resolved.

I just tested on the latest version and currentHitStreak is working perfectly. I must have been on an older version.
