### ISSUE TITLE
Delay within "SongStart" causing loops.

### ISSUE THREAD

**Issue by BoomSoMuch** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#123]
I put delays within my "SongStart" action so that things on OBS happen a few seconds after each other.

During this time, when the timer triggers the main script, it activates the "SongStart" action again. Everything within the "SongStart" repeats over and over until all the delays are done.

I have a workaround, I made a second action called "SongStart2". I have SongStart do nothing other than trigger SongStart2. That seems to let the main script move on. Then SongStart2 has my delays and everything else.

I haven't tested the endsong to see if it has a similar behavior.

EDIT - I know you are super busy! This is totally low priority since there is an easy workaround. I appreciate your work!!

**Comment by Th0rstenf** [comment]
Putting this in work, as it is already fixed on the branch for the guessing game

**Comment by Th0rstenf** [comment]
Fixed in version 0.3.0 by switching to custom triggers and having actions in a separate non blocking queue
