### ISSUE TITLE
Extend WhiteList defaults with some other scenes whitelisted

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#37]
I wanna have the opposite of the BlackList.

In Short: 
**Option 1**:
White List should be the 3 default scene (menuScene, pauseScene, songScene) + whiteList: a list of scenes what is equals with songScene. This way, Sceneswitcher switches to songScene always, but it is ok to switch if it is in some whitelist scene.

**Option 2**:
We could have like menuScene, pauseScene, and a list of songScenes. This way, we do not need the Whitelist.
This way, Sceneswitcher could switch any of the songScene scenes, but maybe could take one randomly, or could use the first always from the WhiteList.

----------- More in details:
Usecase is, that I got:
- menuScene: RSMenu
- pauseScene: RSPause
- songScene: RSSongScene1, RSSongScene2, RSSongScene3, RSSongScene4, RSSongScene5
- and lets say, I got 3 more other Scenes, not for Rocksmith, like StreamStart, StreamEnd, Break

So actually 1 for menu, 1 for pause and 5 different scenes when I play a song (what I rotate with advanced scene switcher plugin in OBS). Plus 3 more not RS related scenes.

I have to add to BlackList: StreamStart, StreamEnd, Break what is not a big deal.
But what, if I add a new scene suddenly like the new scene ZoomIn, I have to add this to the BlackList. Otherwise, if I am in ZoomIn, the switcher will move to some RS scene. So it would be better, if I just extend the WhiteList with new RS scenes if I add, and do not bother with other scenes, not RS related. This is also good, if I switch the SceneCollection to a different one. Then scene switcher will (try) to switch to some RS scene. If White List, then don't.
More likely, people will add new other scenes, rather than new RS scene...I think.

**Comment by Th0rstenf** [comment]
@kozaka-tv I'm not entirely sure why you want so many RS scenes, (personally I prefer nesting them), but it can be done.
I'd probably go for option 2.
Would it be sufficient if it always starts with the first scene in the list, or do you want that to be configurable?
If yes, which option should be available?

**Comment by kozaka-tv** [comment]
Yeah, to nest them could work. I have this setup from the old time, when we could not add in OBS a scene into an another scene, and also the Advanced Scene Switcher, what I am using to switch between this scenes, could not go deep into a scene that time, but now it could. I have to check. However, option 2 would I think also good. Gives the flexibility into the hand of the streamer.

I think to take the first from the list as default songScene to switch could be enough. Important is, that in case the whitelist is checked, it will NOT switch if we are NOT in any of the whitelist scene (menu, song scene list, pause). Because very likely, I do add some effect scene or something, what is maybe not used during a song, and disturbs the flow if I forgot to add. If I would do the programming, I would add all those scenes into a variable called whiteListScenes or similar, and then compare with the actual OBS scene. This white list is what I missed from the old scene switchter.

The first part of my Scenes are the "views" what I show in my stream, the bottom parts are scenes I integrate into some of the top part:

![image](https://user-images.githubusercontent.com/4964462/220912086-4d719b62-de95-4503-b0b3-8b0bbcba386f.png)

**Comment by Th0rstenf** [comment]
In order to be compatible with previous configurations, my idea would be:
Allowing the addition multiple song scenes -> will be active during all of those in white list behavior.
Always start with the first one when starting a song.
Jump back to the last one, if the game was paused and resumed.

Would that be sufficient for you @kozaka-tv ?

**Comment by Th0rstenf** [comment]
And I don't want to add an implicit switch to a solo scene, this is better performed in enterSolo/leaveSolo. Also the switch to other song scenes .
As long as all of those are in the list of songscenes, it will continue to work.

**Comment by Th0rstenf** [comment]
@kozaka-tv Please have a look at the linked pull request. Would that help already? Keep in mind i'll probably implement #47 before the next release as well
