### ISSUE TITLE
Add soloScene to be able to define an OBS scene in case enterSolo in song

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#38]
Please add a solo scene (or scenes) option what we could use to set up an automatic enter solo scene switch!

We should be able to set:
- That is this automation turned on or off.
- A list of solo scenes.
- A timeout in seconds (should exists some default like 15 seconds)

1. In case, the song enters to solo (enterSolo), SW should switch to the first scene from the solo scenes in case it is allowed (not in a blacklisted scene for example).
2. If solo is over (leaveSolo), it should return to an allowed song scene.
3. If the timer is over, it should return to an allowed song scene.
4. If the song is over, it should switch back to menu scene.
5. If the song is paused, it should switch to pause scene.
6. Question: after resume, should switch back to last scene or to the first songScene?

I am thinking what could this bring to us...well...with SB it is just working. However, as the example shows below, it is working with SB, but if the charts are so unreliable, we must have some logic to switch off from solo scene automatically. So actually points 2-5 (and 6) are good.

**Comment by kozaka-tv** [comment]
I tested the enter and leave solo actions in SB yesterday and I am afraid that we can not use the chart's leave and enter solo attributes, because they are most likely missing the leave or enter, missing at all, are wrongly placed...so it is just not reliable. I do not know, but probably for bass chart, charters could define a different solo part. As the guitar solo, or a bass solo, could be in different parts of a song.

How ever, here is an example: Ozzy Osbourne -  Crazy Train (Studio) - **on bass**
Creator: [fabianosan](https://ignition4.customsforge.com/profile/fabianosan)
https://ignition4.customsforge.com/cdlc/529

At 26:21 switcher detects the solo (how ever, there were no guitar or bass solo in that part of the song...it was verse):

![image](https://user-images.githubusercontent.com/4964462/220918496-ae0fedae-ad1d-4a26-adb6-ee8ad214d248.png)

And after 3-4 seconds it enters into solo scene of my:

![image](https://user-images.githubusercontent.com/4964462/220918746-152fdb34-8628-4efb-8b88-77dfaf80aa20.png)

Detects leaveSolo:

![image](https://user-images.githubusercontent.com/4964462/220919375-673e167d-b857-48e2-ba19-43615ee231e4.png)

but did not switched back, so I kicked back to songScene:

![image](https://user-images.githubusercontent.com/4964462/220919617-47bf8224-c354-4c75-afdf-b09d7939b1a8.png)

In the middle of a guitar solo, it detects enterSolo:

![image](https://user-images.githubusercontent.com/4964462/220919770-efcc11d0-2645-4459-b4c8-576d3b869388.png)

And switches to solo scene:

![image](https://user-images.githubusercontent.com/4964462/220919853-a2688883-3d95-4f49-b6ec-a70d5f004269.png)

Song ended, but because it was in solo scene and there was no leaveSolo, and I used whitelist settings, it stuck in the solo scene.

![image](https://user-images.githubusercontent.com/4964462/220920430-be722835-99e5-4a2c-954f-0c40ec72e9cb.png)

So, it is worked, but was not good.

**Comment by kozaka-tv** [comment]
My SB settings:

enterSolo:

![image](https://user-images.githubusercontent.com/4964462/220928106-bcd1019a-1a1b-4f92-866f-ccb27abf3695.png)

leaveSolo:

![image](https://user-images.githubusercontent.com/4964462/220928203-ecd6b9e0-4adf-4f99-8a8d-3a45b56a1f01.png)

**Comment by kozaka-tv** [comment]
Oh now I know why leaveSolo does not worked! Because I used whitelist, and it was not in the menu, pause or song scene, it just not switched back at leaveSolo detection to song. What is ok, so it was my fault :)

![image](https://user-images.githubusercontent.com/4964462/220929618-ef04f25e-c7ff-4f98-a843-5c51bf12dac2.png)

**Comment by Th0rstenf** [comment]
As this was mostly misusage. I close this request and add a warning to the readme
