### ISSUE TITLE
Wait a couple of seconds before switch back to menuScene

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#39]
I experienced, that Sniffer send the information, that the song ended a bit earlier than really the chart ends. And this means, like 3 seconds before the chart ends, we land already in the menuScene from the songScene. It would be great, if the switcher would wait a couple of seconds before to it switch back to menuScene.

It would be great if this should have a default value in seconds (or milliseconds), but the user could this set to a different value.
Or if this could be turned off, in case the user do not want to have this function.

In case, we are going from pauseScene into songScene, this delay should be not used. It just has to switch right away.

I do not know, what happens, if Streamerbot triggers again the Switcher during this delay or the switcher blocks the bot? Or the bot will not trigger in case the switcher is not finished the work? This must be for sure considered!

**Comment by kozaka-tv** [comment]
I have rethink this a bit, and I think we could maybe remove this minDelay logic. I am not checked everything, but for me, it would be better if the switcher just switching if it is needed. Without delay. But maybe to check every second is not good...idk.

Maybe we could introduce some, by the user also configurable delays at song start, end time and solo start/end time (if solo introduced). But actually, a delay could be added by the user also in the actions....so. If the built in delay is gone, users could just add delay (like at song end).

For example, at the

**Comment by Th0rstenf** [comment]
> I have rethink this a bit, and I think we could maybe remove this minDelay logic. I am not checked everything, but for me, it would be better if the switcher just switching if it is needed. Without delay. But maybe to check every second is not good...idk.
> 
> Maybe we could introduce some, by the user also configurable delays at song start, end time and solo start/end time (if solo introduced). But actually, a delay could be added by the user also in the actions....so. If the built in delay is gone, users could just add delay (like at song end).
> 
> For example, at the

I'm under the impression that you still misunderstand the delay.It does only delay after a switch, e.g. if you'd continously hit ESC -> resume during a song, it wouldn't switch every single second.
It does not always delay. faster switches than that would only be annoying, not add any benefit.

**Comment by Th0rstenf** [comment]
as part of #65 this _minDelay_ was moved to SceneInteractor and renamed to cooldownPeriod to make it more clear.
A general delay doesn't make sense imho, but a cooldown period really does. So i'll close this for now.

If you want, the cooldown period could be made configurable, but if you like that please open another issue for it
