### ISSUE TITLE
Refactoring to prepare for addition of unit tests

### ISSUE THREAD

**Issue by Th0rstenf** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#46]
To keep up with rising complexity, automated SW tests could help as quality gate. If a suitable solution was implemented, a test driven approach for extensions would be encouraged.

**Comment by Th0rstenf** [comment]
@kozaka-tv Do you happen to know any good test frameworks for C#?

**Comment by kozaka-tv** [comment]
Not really. 

https://www.lambdatest.com/blog/nunit-vs-xunit-vs-mstest/
https://saucelabs.com/resources/blog/nunit-vs-xunit-vs-mstest-with-examples

**Comment by kozaka-tv** [comment]
But I would take NUnit Test I think.

**Comment by Th0rstenf** [comment]
Alright, then it will be NUnit, will still take some time to refactor.

In order to have cleaner public interfaces, i'd pack fetching and parsing the json to a nested class, and the whole evaluation to another. Then i'd suggest focussing on the second nest class in testing.

**Comment by Th0rstenf** [comment]
I've already spend a few hours on the refactoring itself, should be finished soonish (as soon work permits me to continue)
I think this issue should be split into the refactoring itself, and then adding the test cases in a separate issue

**Comment by kozaka-tv** [comment]
What I do not like, is the global variables. I think it would be better, to have 1-2 record classes for the data.

1) For config
2) For variables like currentScene, sniffer status, etc
( 3) If needed... etc.)

And then, classes/methods could get those records as input. This way, we could call a method with any input, and test it.

https://www.baeldung.com/cs/global-variables

I do not know, that in SB we could use different files, like a real structured code, but most likely not. Only one file could be added and inside this, we have to do everything (this is the Program.cs). So we have to do everything in that single file. But test could be separated and, structured. Like one test the config read, the other the isRelevant Method or class, etc.

If, there would be an option, that somethhing assemble everything into one file, that would be great. Then we could split up Program.cs to smaller pieces, and then at release time (or during dev), we just assemble the Program.cs and then use it. That would be great. Idk that is this possible somehow....just thinking :)

**Comment by Th0rstenf** [comment]
They are not really global variables, they are still in CPHInline.
It seems that NUnit offers methods to directly access those private
attributes for testing as well, so this solves the problem most likely.

If you check the refactoring branch (still not finished though) it's
already separating scene interactions, parsing the records from Sniffer and
evaluating those records.

Am Mi., 22. März 2023 um 12:27 Uhr schrieb Kozaka ***@***.***
