### ISSUE TITLE
Read out values like scene settings from a config file for the Mock

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#52]
It would be a bit better if a local settings file is read by the Mock code and this is used locally rather than having this hardcoded in the CPHmock.

File could be named as: config.ini
This should be set as ignored in the .gitignore file as this should be actually never be committed and pushed into the repository.

Currently those attributes should be configurable in the config.ini file:

snifferIP
snifferPort
songScenes
menuScene
pauseScene
sectionDetection
behavior
switchScenes
sectionActions
blackList

**Comment by Th0rstenf** [comment]
Solid Idea. Go for it :)
