### ISSUE TITLE
Error messages in chat should be configurable by the user

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#53]
If Sniffer is not started we get this messages:

![image](https://user-images.githubusercontent.com/4964462/223173538-8bb33225-e51e-4387-b885-c0fe32c9c6b9.png)

It would be great if we could set those messages in a config for local and as a variable in SB.

To reproduce, turn off Sniffer and turn log to chat on: doLogToChat = true;

**Comment by Th0rstenf** [comment]
Configuring Error messages is a pretty bad idea. If users get those parameters, they will be at best confused, and at worst change the content in a way that the log file will no longer provide any value

**Comment by Th0rstenf** [comment]
And doLogToChat is probably no longer necessary. It was introduced before the mockup was created to debug in an IDE. It was definetly never intended to be exposed to a regular user (with 1Hz it would flood chat horribly anyway)

**Comment by kozaka-tv** [comment]
Ah ok...then Actually, this could be changed to remove this function. I turned on the feature, and went away from PC for hours. :) My chat was full with this messages.

If the intention is not to provide useful information in the chat for the viewers, so if it is only for debug, then yes, this change is invalid. Maybe let's convert it to remove the log to chat parts?

**Comment by Th0rstenf** [comment]
@kozaka-tv I will remove it while refactoring for #46 
This can be closed
