### ISSUE TITLE
System.OverflowException in ResponseParser.SaveNoteDataIfNecessary()

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#64]
After 2 hours of using RS2SB, I experienced an OverflowException. I assume (so far I could) that there is a variable, what is used lot of memory...but this is a guessing only.

Error:
[2023-03-31 20:16:07.609 INF] RS2SB :: setCurrentScene to 'ROCKSMITH pause'
[2023-03-31 20:16:09.639 WRN] RS2SB :: Caught exception: Az aritmetikai művelet túlcsordulást eredményezett.
[2023-03-31 20:16:09.640 ERR] InlineCode :: There was an error running the instance for ''
System.Exception: RS2SB :: Caught unknown exception when trying to write song meta data: Az aritmetikai művelet túlcsordulást eredményezett. ---> System.OverflowException: Az aritmetikai művelet túlcsordulást eredményezett.
   a következő helyen: c74f23cf29c54470b9c7ffca8818c269.CPHInline.ResponseParser.SaveNoteDataIfNecessary()
   a következő helyen: c74f23cf29c54470b9c7ffca8818c269.CPHInline.Execute()
   --- Vége a belső kivételek veremkivonatának ---
   a következő helyen: c74f23cf29c54470b9c7ffca8818c269.CPHInline.Execute()
   a következő helyen: _rgMS3SG4P71afX4XfwKD1eNSbEN._sohcTcFFlDFEhwC8ntXLDgc7aTJb(Dictionary`2 , Boolean , String )
   a következő helyen: _rgMS3SG4P71afX4XfwKD1eNSbEN._sohcTcFFlDFEhwC8ntXLDgc7aTJb(Dictionary`2 , Boolean , String )
   a következő helyen: _4qwQ4ZO2BnD0Dy0dro3XnQR6EnO._1MAeAEhpCVOAJxFDXk8c6VFWutUA(Guid , _neft6zrZ0ed4xQXab3KGQDG48bY , Dictionary`2 , Boolean , String , Boolean )
   a következő helyen: _co3Ieo5TpUCB2SMO675rZSqQhVR._cBzAV64fRE5jk78sn9u9P3f8Z9j.MoveNext()

And this was repeated till I did not reastart SB.

The #60 ( #62 ) branch was, what I used.

**Comment by Th0rstenf** [comment]
Interesting, it shouldn't depend on the branch though. 
Must be coming from this block:

`
 if (lastNoteData != null)
                        {
                            additionalNotesHit = (uint)(currentResponse.MemoryReadout.NoteData.TotalNotesHit -
                                                        lastNoteData.TotalNotesHit);
                            additionalNotesMissed = (uint)(currentResponse.MemoryReadout.NoteData.TotalNotesMissed -
                                                           lastNoteData.TotalNotesMissed);
                            additionalNotes = (uint)(currentResponse.MemoryReadout.NoteData.TotalNotes -
                                                     lastNoteData.TotalNotes);
                        }
                        else
                        {
                            additionalNotesHit = (uint)(currentResponse.MemoryReadout.NoteData.TotalNotesHit);
                            additionalNotesMissed = (uint)(currentResponse.MemoryReadout.NoteData.TotalNotesMissed);
                            additionalNotes = (uint)(currentResponse.MemoryReadout.NoteData.TotalNotes);
                        }

                        totalNotesHitThisStream += additionalNotesHit;
                        totalNotesMissedThisStream += additionalNotesMissed;
                        totalNotesThisStream += additionalNotes;
`
I'm not entirely sure what happened here. I highly doubt that you have played more than 4 billion notes  within a couple of hours. 
lastNoteData is properly nulled when entering a song, so underflows in the calculation shouldn't happen either.

We should add some verbose logging here to get the actual numbers. Currently I do not have a theory what might have happened here.
In any case we should catch that exception, just not sure how to handle it. Looking at the code i'm confident you could stream for weeks without that happening (Assuming you could play rocksmith without a break for 4 weeks, it would still take an average of 1775 notes PER SECOND to have an overflow in the total number of notes)

Any theory what went wrong?

**Comment by Th0rstenf** [comment]
Instead of verbose logging we could also wrap it in a try/catch. If we catch it, we log all relevant numbers as debug, and do not update lastNoteDate. If it is caused by some kind of Rocksniffer hickup, we could fully recover.

What do you think @kozaka-tv ?

**Comment by kozaka-tv** [comment]
I could easily play 4 billion notes in one streams! :)))) First I experienced this problem was at 2023-03-30. I wrote just, that the branch what I am using during my stream is the #60 . Maybe it has really nothing to do with it, idk.

Would be perfect if we could know the exact line number. I do not know why and where it happened. This code part is to complex...and even do not know, why the switcher does need this totals. I will do some testing, and try to figure out how to log out the current lines. Then we could catch all exceptions there and write out the current line + variable values.

I can imagine, that this is an SB problem somehow. Maybe the setGlobalVar throws the exception?

**Comment by Th0rstenf** [comment]
I'm sceptical, in that case the error message would mention the call to SetGlobalVar.
It's much more likely that malformed data from the sniffer caused some shenanigans here

**Comment by kozaka-tv** [comment]
Reproducible:

1) Start play a song --> In song
2) Push Esc --> Pause
3) Push Restart --> Exception occurs

**Comment by kozaka-tv** [comment]
Sorry, but still not ok!

![image](https://user-images.githubusercontent.com/4964462/230196591-dc6db086-ac31-498f-abb9-1b14538ed9d4.png)

**Comment by Th0rstenf** [comment]
No need to be sorry. If it's not ok it needs fixing :)
I'll create a new issue for it though to get a fresh branch. The handling with reopening issues whose branches are already deleted seems not that user friendly

**Comment by kozaka-tv** [comment]
Ok, but I made here smaller changes. I will create a pull request fast.

**Comment by Th0rstenf** [comment]
New issue created.
