### ISSUE TITLE
Add an option to disable the automatic scene switching

### ISSUE THREAD

**Issue by Th0rstenf** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#72]
Name of the variable should be: songSceneAutoSwitchMode
First values, solved in this issue should be:
- off
- sequential
Default, if not given, or wrong: off

Sequential is the old solution. switchScenes variable could stay in Program, but not needed then as a Global variable. As:
- if songSceneAutoSwitchMode=off --> switchScenes=false
- if songSceneAutoSwitchMode=sequential --> switchScenes=true

Or, values could be like:
- o
- s
- (r for later implemented in #76)

**Comment by kozaka-tv** [comment]
I added songSwitchPeriod to readme.md in #67, but maybe a new Global variable should be added to enable or disable this. That way we could turn automatic switching on/off in SB on the run.

**Comment by Th0rstenf** [comment]
> I added songSwitchPeriod to readme.md in #67, but maybe a new Global variable should be added beside the songSwitchPeriod to enable or disable this. That way we could turn automatic switching on/off in SB on the run but keep the value "fixed" in config.

I think this can be combined with #76
