### ISSUE TITLE
Create project in github

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#74]
It would be great, if we would use the Projects function here on Github. Then:

- We could se the progress of the specific issues
- Create a release note with ease

I think the default columns/states should be enough, or when not, maybe:
- Todo
- In Progress
- Review
- Test
- Done
A simple Kanban board kind of.

Only you @Th0rstenf can create a new Project here.

**Comment by Th0rstenf** [comment]
I created a project using the backlog template, but i'm not sure how access management is implemented here. Can you check if you already have access @kozaka-tv ?

**Comment by Th0rstenf** [comment]
And it wasn't. You should be able to see it now :) @kozaka-tv

**Comment by kozaka-tv** [comment]
All visible!

**Comment by kozaka-tv** [comment]
But now, issues should be added always to project. So far I remember, there could be some automation regarding this.

**Comment by Th0rstenf** [comment]
I do not see anything to automate that.
@kozaka-tv maybe we should agree on adding issues via the project directly? (add item button in each lane can create an issue)

**Comment by kozaka-tv** [comment]
This is what I ment:

![image](https://user-images.githubusercontent.com/4964462/230225866-c230260c-1c83-4f07-b9a6-6cebe2443f17.png)

I turned on.
