### ISSUE TITLE
Add an option to make automatic scene switch to a random scene

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#76]
It is nice to have automatic scene switching, but it would be good if the songScene selection would be random. So not sequential, rather than randomly chosen, which one will be set.

New value for songSceneAutoSwitchMode: random or r (depending on the realisation in #72)
The process, if enabled (songSceneAutoSwitchMode=random), have to switch between the songScenes randomly.

**Comment by Th0rstenf** [comment]
Nice Idea. However I would also add a configuration option to make it selectable. Just in case someone prefers it being predictable.

**Comment by kozaka-tv** [comment]
Yes...like: automaticSceneSwitchMode: sequential | random | off
With off, we could turn this function off. What you think?

**Comment by kozaka-tv** [comment]
I will name it songSceneAutoSwitchMode
