### ISSUE TITLE
Add an option to make automatic scene switch time for each scene different.

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#77]
We should be able to set a fixed, or range value for each songScene to set the time how long a scene should be set in OBS/SLOBS.

Like I have songScenes: Scene1, Scene2, Scene3, Scene4
And there should be an new option for scene time during a song play like for example: 10, 3-20, 5, 15

So this means, if it is switched to:
- Scene1, it will be shown 10 second long
- Scene2, **randomly between 3 and 20 seconds**
- Scene3, 5 seconds
- Scene4, 15 seconds

Or similar... (it is a pity, that in SB we could set timer minimum only to 1 sec...I would have more faster stuffs).

This could replace the Advanced scene switcher for most users.

--- 
Or songScenes="Scene1#10, Scene2#3-20, **Scene3**, Scene4#15"
Same as above, but Scene3 will use the songSwitchPeriod set in config, or some default if this is not set.

**Comment by Th0rstenf** [comment]
I wonder if we should make the syntax a bit more explicit, so it is less cryptic for the user
But if we do, it has the potential to be bloated quite fast.

I just get started on it, but if you have other ideas about the syntax, feel free to drop them here :)

**Comment by Th0rstenf** [comment]
I'm still not convinced that having a config file is the way to go (see the arguments I had for closing #84 as won't be implemented)
We can open a discussion about that though.

**Comment by kozaka-tv** [comment]
Yeah...I converted #84 into a Discussion. Config file brings nothing in our case.
