### ISSUE TITLE
Enable discussions on Github

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#86]
Maybe it is better to enable Discussions, and then discuss stuffs there like logging, or anything. And then create an issue if it is agreed what to do or so.

What you think?

Like this:
![image](https://user-images.githubusercontent.com/4964462/230432553-07095423-cabe-4059-926e-ee541ab080af.png)

**Comment by Th0rstenf** [comment]
Excellent idea!
