### ISSUE TITLE
Provide global access to variable access abstraction

### ISSUE THREAD

**Issue by Th0rstenf** [Th0rstenf/Rocksniffer-to-Streamer.bot-extension#94]
Wrapping all variable access is not a bad idea, but it should be in a separate subclass, so it can be passed to other subclasses.
If we introduce an abstraction layer, it needs to available everywhere. A singleton access or static methods would totally be acceptable here.

_Originally posted by @Th0rstenf in https://github.com/Th0rstenf/Rocksniffer-to-Streamer.bot-extension/pull/93#discussion_r1161253220_

**Comment by kozaka-tv** [comment]
I do not get, what you ment here! :)

**Comment by Th0rstenf** [comment]
Added with 0.3.0
